---
version: '3'

vars:
  BIN_CODEFORMAT: ~/.local/opt/EmmyLuaCodeStyle/bin/CodeFormat

tasks:
  default:
    cmds:
      - task: format
      - task: lint_and_test

  lint_and_test:
    deps: [lint, test]

  format:
    deps: [format_lua]

  lint:
    deps: [lint_lua, lint_shell]

  format_lua:
    cmds:
      - '{{.BIN_CODEFORMAT}} format --config .editorconfig --workspace lua'

  lint_lua:
    cmds:
      - '{{.BIN_CODEFORMAT}} check --config .editorconfig --diagnosis-as-error --workspace lua'

  lint_shell:
    cmds:
      - shellcheck *.sh

  test:
    cmds:
      - ':'
