---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

      - name: Set up cache path
        run: echo "CACHE_PATH_EmmyLuaCodeStyle=$HOME/.local/opt/EmmyLuaCodeStyle" >> $GITHUB_ENV

      - name: Cache EmmyLuaCodeStyle
        id: cache-emmylua
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATH_EmmyLuaCodeStyle }}
          key: emmylua-1.5.6

      - name: Download and extract EmmyLuaCodeStyle
        if: steps.cache-emmylua.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/.local/opt
          wget -q https://github.com/CppCXY/EmmyLuaCodeStyle/releases/download/1.5.6/linux-x64.zip -O /tmp/linux-x64.zip
          unzip -q /tmp/linux-x64.zip -d /tmp/
          mv /tmp/linux-x64 $HOME/.local/opt/EmmyLuaCodeStyle
          chmod a+x $HOME/.local/opt/EmmyLuaCodeStyle/bin/*

      - name: Verify installation
        run: ls -l $HOME/.local/opt/EmmyLuaCodeStyle


      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task -p lint
      - run: task -p test
